# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [2]:
defaults = np.seterr(all="ignore")
val = np.ones(1) / 0

_ = np.seterr(**defaults)


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [5]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
False

nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [8]:

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')



print(yesterday)
print(today)
print(tomorrow)

2024-03-23
2024-03-24
2024-03-25


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [9]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [60]:
val = np.random.uniform(0,10,10)
print(val)

print (val-val%1)
print (np.floor(val))
print (np.ceil(val)-1)
print (val.astype(int))
print (np.trunc(val))

[3.05271228 8.24344838 8.14020808 5.34924457 2.42315454 4.11821325
 1.8320361  4.37611144 9.29120572 0.87591041]
[0.05271228 0.24344838 0.14020808 0.34924457 0.42315454 0.11821325
 0.8320361  0.37611144 0.29120572 0.87591041]
[3. 8. 8. 5. 2. 4. 1. 4. 9. 0.]
[3. 8. 8. 5. 2. 4. 1. 4. 9. 0.]
[3 8 8 5 2 4 1 4 9 0]
[3. 8. 8. 5. 2. 4. 1. 4. 9. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [11]:
val=np.zeros((5,5))
val +=np.arange(5)
print(val)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [16]:
def generate():
    for x in range(10):
        yield x
val= np.fromiter(generate(),dtype=float)
print(val) 

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [20]:
val=np.linspace(0,1,11, endpoint=False)[1:]
print(val)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [21]:
val=np.random.random(10)
val.sort()
print(val)

[0.00185353 0.22912884 0.25214865 0.28390728 0.44490051 0.47442516
 0.65167808 0.77661413 0.93901602 0.97684735]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [26]:
arr1=np.arange(1,4)

val=np.add.reduce(arr1)
print(val)

6
6


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [33]:
arr1=np.random.random(10)
arr2=np.random.random(10)

#if he two have same shape and elements
equal=np.array_equal(arr1,arr2)
print(equal)
#if the two arrays elementwise equal within a tolerance
equal=np.allclose(arr1,arr2)
print(equal)



False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [35]:
arr=np.random.random(5)

arr.flags.writeable=False
arr[3]=1
print(arr)

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [53]:
val=np.random.random((10,2))

x,y=val[:,0],val[:,1]

arr=np.sqrt(x**2 + y**2)
print(arr)

pol=np.arctan2(x,y)
print(pol)


[0.23202252 1.24203496 0.65546078 0.7810435  0.54727991 0.84142992
 0.48675009 0.73013868 1.04036029 1.03947734]
[0.2652301  0.87616372 1.14184927 0.03999165 0.42121502 1.17058645
 0.69605657 1.19198926 1.22363541 0.77488153]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [57]:
val=np.random.random(10)
val[val.argmax()]=0
print(val)


[0.29472488 0.         0.13161926 0.79993845 0.26367248 0.06448422
 0.51277022 0.75731146 0.11885841 0.76756455]
